"""align_data_contract

Revision ID: ca83e8b0a3f2
Revises: 0001
Create Date: 2026-09-24 01:48:24.419111+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca83e8b0a3f2'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_task_schedule', 'schedule_id',
               existing_type=sa.UUID(),
               comment='Specification field: Schedule ID — unique schedule entry',
               existing_comment='Specification field: Schedule ID',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'task_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Specification field: Task ID — links to task_history.task_id',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Specification field: Operator ID',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'machine_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Specification field: Machine ID',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'scheduled_date',
               existing_type=sa.DATE(),
               comment='Specification field: Scheduled Date — calendar date of the task',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'scheduled_time',
               existing_type=postgresql.TIME(),
               comment='Specification field: Scheduled Time — start time of the task',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'task_status',
               existing_type=sa.VARCHAR(length=50),
               comment="Specification field: Task Status — e.g. 'UPCOMING', 'CURRENT', 'COMPLETED', 'DELAYED', 'CANCELLED'",
               existing_nullable=False,
               existing_server_default=sa.text("'Scheduled'::character varying"))
    op.alter_column('incident', 'incident_id',
               existing_type=sa.UUID(),
               comment='Specification field: Incident ID — unique incident identifier',
               existing_comment='Specification field: Incident ID',
               existing_nullable=False)
    op.alter_column('incident', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Specification field: Timestamp — when the incident occurred',
               existing_nullable=False)
    op.alter_column('incident', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Specification field: Operator ID — may be null if not yet identified',
               existing_nullable=True)
    op.alter_column('incident', 'machine_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Specification field: Machine ID — may be null if not yet identified',
               existing_nullable=True)
    op.alter_column('incident', 'event_type',
               existing_type=sa.VARCHAR(length=200),
               comment='Specification field: Event Type — category of event',
               existing_nullable=False)
    op.alter_column('incident', 'severity',
               existing_type=sa.VARCHAR(length=50),
               comment="Specification field: Severity — e.g. 'Low', 'Medium', 'High', 'Critical'",
               existing_nullable=False)
    op.alter_column('incident', 'description',
               existing_type=sa.TEXT(),
               comment='Specification field: Description — free-text event description',
               existing_nullable=True)
    op.alter_column('incident', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment="Specification field: Status — e.g. 'Active', 'Resolved', 'Historical'",
               existing_nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    op.alter_column('machine_fault', 'task_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Source field: Task ID — links to task_history.task_id',
               existing_nullable=True)
    op.alter_column('machine_fault', 'machine_status',
               existing_type=sa.VARCHAR(length=100),
               comment="Source field: Machine Status — e.g. 'NORMAL', 'DEGRADED', 'UNAVAILABLE'",
               existing_nullable=False)
    op.alter_column('machine_fault', 'fault_type',
               existing_type=sa.VARCHAR(length=200),
               comment="Source field: Fault Type — e.g. 'NONE', 'TIRE_PUNCTURE', 'HYDRAULIC_FAULT', etc.",
               existing_nullable=True)
    op.alter_column('machine_fault', 'downtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Source field: Downtime — minutes of machine downtime (0 if operational)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.add_column('task_history', sa.Column('machine_id', sa.String(length=100), nullable=True, comment='Specification field: Machine ID'))
    op.add_column('task_history', sa.Column('operator_id', sa.String(length=100), nullable=True, comment='Specification field: Operator ID'))
    
    op.execute("""
        UPDATE task_history
        SET machine_id = dts.machine_id,
            operator_id = dts.operator_id
        FROM daily_task_schedule dts
        WHERE task_history.task_id = dts.task_id
    """)

    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM task_history WHERE machine_id IS NULL OR operator_id IS NULL) THEN
                RAISE EXCEPTION 'Backfill failed: Some task_history rows could not be matched to daily_task_schedule';
            END IF;
        END $$;
    """)

    op.alter_column('task_history', 'machine_id', nullable=False)
    op.alter_column('task_history', 'operator_id', nullable=False)

    op.execute("UPDATE machine_fault SET machine_status = 'NORMAL' WHERE machine_status = 'Operational'")
    op.execute("UPDATE machine_fault SET machine_status = 'UNAVAILABLE' WHERE machine_status = 'Fault'")
    op.execute("UPDATE daily_task_schedule SET task_status = 'UPCOMING' WHERE task_status = 'Scheduled'")
    op.execute("UPDATE daily_task_schedule SET task_status = 'CURRENT' WHERE task_status = 'In Progress'")
    op.execute("UPDATE incident SET status = 'Active' WHERE status = 'Open'")
    op.alter_column('task_history', 'task_type',
               existing_type=sa.VARCHAR(length=200),
               comment='Source field: Task Type — category of work performed',
               existing_nullable=False)
    op.alter_column('task_history', 'weather',
               existing_type=sa.VARCHAR(length=100),
               comment='Source field: Weather — conditions during the task',
               existing_nullable=False)
    op.alter_column('task_history', 'operator_skill',
               existing_type=sa.VARCHAR(length=100),
               comment="Source field: Operator Skill — e.g. 'Beginner', 'Intermediate', 'Expert'",
               existing_nullable=False)
    op.alter_column('task_history', 'machine_age',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Source field: Machine Age — age of the machine in years',
               existing_nullable=False)
    op.alter_column('task_history', 'estimated_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Source field: Estimated Time — planned task duration (hours)',
               existing_nullable=False)
    op.alter_column('task_history', 'actual_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Source field: Actual Time — real task duration (hours)',
               existing_nullable=False)
    op.create_index(op.f('ix_task_history_machine_id'), 'task_history', ['machine_id'], unique=False)
    op.create_index(op.f('ix_task_history_operator_id'), 'task_history', ['operator_id'], unique=False)
    op.alter_column('telemetry', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Source field: Timestamp',
               existing_nullable=False)
    op.alter_column('telemetry', 'machine_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Source field: Machine ID',
               existing_nullable=False)
    op.alter_column('telemetry', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Source field: Operator ID',
               existing_nullable=False)
    op.alter_column('telemetry', 'engine_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Source field: Engine Hours — cumulative engine run-time in hours',
               existing_nullable=False)
    op.alter_column('telemetry', 'fuel_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Source field: Fuel Used — fuel consumed (litres or unit from source)',
               existing_nullable=False)
    op.alter_column('telemetry', 'load_cycles',
               existing_type=sa.INTEGER(),
               comment='Source field: Load Cycles — number of load/dump cycles',
               existing_nullable=False)
    op.alter_column('telemetry', 'idling_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Source field: Idling Time — idle duration in minutes',
               existing_nullable=False)
    op.alter_column('telemetry', 'seatbelt_status',
               existing_type=sa.VARCHAR(length=50),
               comment="Source field: Seatbelt Status — e.g. 'Fastened', 'Unfastened'",
               existing_nullable=False)
    op.alter_column('telemetry', 'safety_alert_triggered',
               existing_type=sa.BOOLEAN(),
               comment='Source field: Safety Alert Triggered — True/False',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetry', 'safety_alert_triggered',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Source field: Safety Alert Triggered — True/False',
               existing_nullable=False)
    op.alter_column('telemetry', 'seatbelt_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Source field: Seatbelt Status — e.g. 'Fastened', 'Unfastened'",
               existing_nullable=False)
    op.alter_column('telemetry', 'idling_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Source field: Idling Time — idle duration in minutes',
               existing_nullable=False)
    op.alter_column('telemetry', 'load_cycles',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Source field: Load Cycles — number of load/dump cycles',
               existing_nullable=False)
    op.alter_column('telemetry', 'fuel_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Source field: Fuel Used — fuel consumed (litres or unit from source)',
               existing_nullable=False)
    op.alter_column('telemetry', 'engine_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Source field: Engine Hours — cumulative engine run-time in hours',
               existing_nullable=False)
    op.alter_column('telemetry', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Source field: Operator ID',
               existing_nullable=False)
    op.alter_column('telemetry', 'machine_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Source field: Machine ID',
               existing_nullable=False)
    op.alter_column('telemetry', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Source field: Timestamp',
               existing_nullable=False)
    op.drop_index(op.f('ix_task_history_operator_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_machine_id'), table_name='task_history')
    op.alter_column('task_history', 'actual_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Source field: Actual Time — real task duration (hours)',
               existing_nullable=False)
    op.alter_column('task_history', 'estimated_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Source field: Estimated Time — planned task duration (hours)',
               existing_nullable=False)
    op.alter_column('task_history', 'machine_age',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Source field: Machine Age — age of the machine in years',
               existing_nullable=False)
    op.alter_column('task_history', 'operator_skill',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Source field: Operator Skill — e.g. 'Beginner', 'Intermediate', 'Expert'",
               existing_nullable=False)
    op.alter_column('task_history', 'weather',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Source field: Weather — conditions during the task',
               existing_nullable=False)
    op.alter_column('task_history', 'task_type',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Source field: Task Type — category of work performed',
               existing_nullable=False)
    op.drop_column('task_history', 'operator_id')
    op.drop_column('task_history', 'machine_id')
    op.alter_column('machine_fault', 'downtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Source field: Downtime — minutes of machine downtime (0 if operational)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('machine_fault', 'fault_type',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Source field: Fault Type — e.g. 'NONE', 'TIRE_PUNCTURE', 'HYDRAULIC_FAULT', etc.",
               existing_nullable=True)
    op.alter_column('machine_fault', 'machine_status',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Source field: Machine Status — e.g. 'NORMAL', 'DEGRADED', 'UNAVAILABLE'",
               existing_nullable=False)
    op.alter_column('machine_fault', 'task_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Source field: Task ID — links to task_history.task_id',
               existing_nullable=True)
    op.alter_column('incident', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Specification field: Status — e.g. 'Active', 'Resolved', 'Historical'",
               existing_nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    op.alter_column('incident', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Specification field: Description — free-text event description',
               existing_nullable=True)
    op.alter_column('incident', 'severity',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Specification field: Severity — e.g. 'Low', 'Medium', 'High', 'Critical'",
               existing_nullable=False)
    op.alter_column('incident', 'event_type',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Specification field: Event Type — category of event',
               existing_nullable=False)
    op.alter_column('incident', 'machine_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Specification field: Machine ID — may be null if not yet identified',
               existing_nullable=True)
    op.alter_column('incident', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Specification field: Operator ID — may be null if not yet identified',
               existing_nullable=True)
    op.alter_column('incident', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Specification field: Timestamp — when the incident occurred',
               existing_nullable=False)
    op.alter_column('incident', 'incident_id',
               existing_type=sa.UUID(),
               comment='Specification field: Incident ID',
               existing_comment='Specification field: Incident ID — unique incident identifier',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'task_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Specification field: Task Status — e.g. 'UPCOMING', 'CURRENT', 'COMPLETED', 'DELAYED', 'CANCELLED'",
               existing_nullable=False,
               existing_server_default=sa.text("'Scheduled'::character varying"))
    op.alter_column('daily_task_schedule', 'scheduled_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Specification field: Scheduled Time — start time of the task',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'scheduled_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Specification field: Scheduled Date — calendar date of the task',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'machine_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Specification field: Machine ID',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Specification field: Operator ID',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'task_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Specification field: Task ID — links to task_history.task_id',
               existing_nullable=False)
    op.alter_column('daily_task_schedule', 'schedule_id',
               existing_type=sa.UUID(),
               comment='Specification field: Schedule ID',
               existing_comment='Specification field: Schedule ID — unique schedule entry',
               existing_nullable=False)
    op.execute("UPDATE incident SET status = 'Open' WHERE status = 'Active'")
    op.execute("UPDATE daily_task_schedule SET task_status = 'In Progress' WHERE task_status = 'CURRENT'")
    op.execute("UPDATE daily_task_schedule SET task_status = 'Scheduled' WHERE task_status = 'UPCOMING'")
    op.execute("UPDATE machine_fault SET machine_status = 'Fault' WHERE machine_status = 'UNAVAILABLE'")
    op.execute("UPDATE machine_fault SET machine_status = 'Operational' WHERE machine_status = 'NORMAL'")
    # ### end Alembic commands ###
