"""
Database operations for the synthetic data generator.
"""
import logging
from typing import List

from sqlalchemy import delete
from sqlalchemy.orm import Session

from app.models.daily_task import DailyTaskSchedule
from app.models.incident import Incident
from app.models.machine_fault import MachineFault
from app.models.task_history import TaskHistory
from app.models.telemetry import Telemetry
from app.core.database import Base

logger = logging.getLogger(__name__)


def reset_phase2_data(db: Session) -> None:
    """
    Clears ONLY the 5 tables generated by Phase 2, in reverse-FK-safe order.
    Does NOT touch alembic_version.
    Rolls back on failure.
    """
    logger.info("Resetting Phase 2 generated data...")
    try:
        # Reverse FK order to avoid constraint violations
        db.execute(delete(DailyTaskSchedule))
        db.execute(delete(MachineFault))
        db.execute(delete(Incident))
        db.execute(delete(Telemetry))
        db.execute(delete(TaskHistory))
        db.commit()
        logger.info("Successfully deleted existing Phase 2 data.")
    except Exception as e:
        db.rollback()
        logger.error(f"Failed to reset Phase 2 data: {e}")
        raise


def bulk_insert_generated_data(db: Session, records: List[Base]) -> None:
    """
    Transactionally inserts all generated ORM objects.
    Rolls back the entire batch if any insertion fails.
    """
    try:
        db.add_all(records)
        db.commit()
    except Exception as e:
        db.rollback()
        logger.error(f"Bulk insert failed: {e}")
        raise
